name: TensuraGame
version: '${version}'
main: fr.erusel.tensura.Main
api-version: 1.16
authors: [ Erusel, Fnafgameur ]
commands:
  tensura:
    description: "Host command for the Game"
    permission: tensura.tensura
  skill:
    description: "Show skills of the player"
  team:
    description: "Select your team here"